### ISSUE TITLE
Howto install?

### ISSUE THREAD

**Issue by horshack** [perlpunk/App-Spec-p5#12]
I don't know how to _install_ this great module, I love the ideas implemented here!

In fact I have the feeling there is nothing like 'perl Makefile.PL; make; make install'. Is the idea for development-time simply to copy lib/App to my current directory und do this:

use lib './lib';
use App::Spec;
...
I wish it would be more fun if I could do it the perl-standard way:

git clone https://github.com/perlpunk/App-Spec-p5.git
cd App-Spec-p5
perl Makefile.PL
make
make install

Thanks for your understanding.
Richard

**Comment by perlpunk** [comment]
thanks!

yeah, at the moment I simply adjust PERL5LIB and PATH when developing.
That's a disadvantage of using Dist::Zilla.
I think I can use a Dist::Zilla plugin though that copies the generated Makefile.PL after building.
Maybe I'll have some time tomorrow to have a look ;-)

**Comment by perlpunk** [comment]
now it has a Makefile.PL
